source/repos/sistema_matricula/sistema_matricula/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using sistema_matricula.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using sistema_matricula.Models.DataAcces;
namespace sistema_matricula.Controllers
{
    public class AlumnoController : Controller
    {


        private Alumno alumnos = new Alumno();

        [HttpGet]
        public ActionResult Listado()
        {
            Alumno objCiclo = new Alumno();
            DataAccessAlumno objDB = new DataAccessAlumno();
            objCiclo.ShowallAlumno = objDB.GetAllAlumno();
            return View(objCiclo);
        }


        [HttpGet]
        public ActionResult Listar()
        {
            Alumno objCiclo = new Alumno();
            DataAccessAlumno objDB = new DataAccessAlumno();
            objCiclo.ShowallAlumno = objDB.GetAllAlumno();
            return View(objCiclo);
        }


        //[HttpGet]
        public ActionResult Agregaralumno()
        {
            return View();
        }


     
        [HttpPost]
        public ActionResult Agregaralumno(Alumno Emp)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    DataAccessAlumno objDB = new DataAccessAlumno();

                    if (objDB.AgregarAlumno(Emp))
                    {
                        ModelState.Clear();
                        ViewBag.Message = "Registro agregado con exito!";
                    }
                }

                return View();

            }
            catch
            {
                return View();

            }
        }

        [HttpPost]
        public ActionResult EditarAlumno(Alumno Alu)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    DataAccessAlumno objDB = new DataAccessAlumno();
                    if (objDB.EditarAl(Alu))
                    {
                        ViewBag.Message = "Registro Editado con exito!";
                    }
                }
                return View();
            }catch
            {
                return View();

            }
        }

        [HttpGet]
        public ActionResult EditarAlumno(int cod)
        {
            if (cod == 0)
            {
                return RedirectToAction("Listado");
            }
            else
            {
                DataAccessAlumno objDB = new DataAccessAlumno();
                Alumno objalumno = new Alumno();
                return View(objDB.ObtenerAlumno(cod));
            }

        }


        [HttpGet]
        public ActionResult DeleteAlumno(int cod)
        {
            if (cod == 0)
            {
                return RedirectToAction("Listado");
            }
            else
            {
                DataAccessAlumno objDB = new DataAccessAlumno();
                //Alumno  objciclo = new Alumno ();
                if (objDB.DeleteAlumno(cod) == true)
                {

                    return RedirectToAction("Listado");
                }
                else
                {
                    return RedirectToAction("Listado");
                }
            }
        }



    }
}

source/repos/sistema_matricula/sistema_matricula/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -MATRICULA</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        .navbar-inverse .navbar-nav > li > a {
            color: #ffffff;
            font-weight:bold
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #0b6d76;color: #fff">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
             
                <div style="margin-top:5px">
                   <h4><i class="glyphicon glyphicon-hdd"></i> SOLIER </h4>

                </div>
  
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li></li>
                    @{
                        if (Session["UserName"] == null)
                        {


                        }
                        else
                        {


                            <li> @Html.ActionLink("Inicio", "Index", "Home")</li>

                            if (Convert.ToString(Session["TipoUser"]) == "Administrador")
                            {

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Escuelas</span> <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Asignatura", "Listado", "Asignatura")</li>
                                        <li>@Html.ActionLink("Carreras", "Listado", "Carreras")</li>
                                        <li>@Html.ActionLink("Facultad", "Listado", "Facultad")</li>
                                        <li>@Html.ActionLink("Ciclo", "Listado", "Ciclo")</li>
                                        <li>@Html.ActionLink("Periodo", "Listado", "Periodo")</li>
                                    </ul>
                                </li>

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Personas</span> <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Alumnos", "Listado", "Alumno")</li>
                                        <li>@Html.ActionLink("Docentes", "Listado", "Docentes")</li>
                                        <li>@Html.ActionLink("Usuario", "Listado", "Usuario")</li>
                                    </ul>
                                </li>

                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true"> <span class="nav-label">Movimientos</span> <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Matricula", "Listado", "Matricula")</li>
                              
                                        <li>@Html.ActionLink("Matriculados", "Listar", "Matricula")</li>
                                        <li>@Html.ActionLink("Tramite", "Listado", "Tramite")</li>
                                        <li>@Html.ActionLink("Pago", "Listado", "Pago")</li>
                                    </ul>
                                </li>
                                <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                            }
                            else if (Convert.ToString(Session["TipoUser"]) == "Alumno")
                            {
                                <li>@Html.ActionLink("Cursos Disponibles", "ListarC", "Asignatura")</li>
                                <li>@Html.ActionLink("Mis Cursos", "Mimatricula", "Matricula")</li>
                                <li>@Html.ActionLink("Pago", "ListadoP", "Pago")</li>

                            }
                            else if (Convert.ToString(Session["TipoUser"]) == "Docente")
                            {
                                <li>@Html.ActionLink("Mis Cursos", "MisAsignaturas", "Asignatura")</li>
                                <li>@Html.ActionLink("Mis Alumnos", "CursosAsignados", "Matricula")</li>
                            }
                            else if (Convert.ToString(Session["TipoUser"]) == "Academico")
                            {
                                <li>@Html.ActionLink("Matriculados", "Listar", "Matricula")</li>
                                <li>@Html.ActionLink("Alumnos", "Listar", "Alumno")</li>
                                <li>@Html.ActionLink("Pago", "Listar", "Pago")</li>
                            }
                            else if (Convert.ToString(Session["TipoUser"]) == "Escuela")
                            {
                                <li>@Html.ActionLink("Matriculados", "Listar", "Matricula")</li>
                                <li>@Html.ActionLink("Alumnos", "Listar", "Alumno")</li>
                                <li>@Html.ActionLink("Pago", "Listar", "Pago")</li>
                            }
                            else if (Convert.ToString(Session["TipoUser"]) == "Director")
                            {
                                <li>@Html.ActionLink("Matriculados", "Listar", "Matricula")</li>
                                <li>@Html.ActionLink("Alumnos", "Listar", "Alumno")</li>
                                <li>@Html.ActionLink("Pago", "Listar", "Pago")</li>
                            }
                            else if (Convert.ToString(Session["TipoUser"]) == "Decano")
                            {

                                <li>@Html.ActionLink("Matriculados", "Listar", "Matricula")</li>
                                <li>@Html.ActionLink("Alumnos", "Listar", "Alumno")</li>
                                <li>@Html.ActionLink("Pago", "Listar", "Pago")</li>
                            }
                            else
                            {




                            }





                            <li> </li>

                            <li> </li>


                            <li class="text-right" style="padding:10px 0px 10px 20px; text-transform:uppercase"><h4>@Session["TipoUser"] : @Session["UserName"]</h4></li>
                            <li style="padding:10px 0px 10px 20px; text-transform:uppercase;color:#ffffff">@Html.ActionLink("Cerrar Sesion", "LogOut", "Login")</li>
                        }
                    }
                </ul>
               




            </div>
        </div>
    </div>
    <div class="container body-content">
        <br /> <br />
        @RenderBody()
        <br /><br />
        <footer>
            <div class="col-lg-12 text-center">  <p>&copy; @DateTime.Now.Year -Sistema de Matricula</p></div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>